android/testing-samples

espresso/BasicSample/app/src/main/res/layout/activity_show_text.xml
espresso/BasicSampleBundled/res/layout/activity_show_text.xml

Update layouts tools.context to reflect current activity name (replace AuxActivity by ShowTextActivity).

Fix activity names associated to BasicSample* layouts

---

README.md

Once in, I'll add it to android-testing-templates.
This fixes #71.

Adds link to ATSL's site to README.md

---

ui/espresso/IntentsBasicSample/app/build.gradle
ui/espresso/IntentsBasicSample/app/src/main/java/com/example/android/testing/espresso/BasicSample/DialerActivity.java
ui/espresso/IntentsBasicSample/app/src/main/res/values/strings.xml

**Problem:**
The app was crashing because the _CALL_PHONE_ permission was missing on devices using API 23.
Related stacktrace:
```
01-02 14:19:09.540 13818-13818/com.example.android.testing.espresso.BasicSample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.android.testing.espresso.BasicSample, PID: 13818
java.lang.IllegalStateException: Could not execute method for android:onClick
at android.view.View$DeclaredOnClickListener.onClick(View.java:4452)
at android.view.View.performClick(View.java:5198)
at android.view.View$PerformClick.run(View.java:21147)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at …
```

Added support to the Marshmallow new permission model

---

unit/BasicSample/app/src/main/java/com/example/android/testing/unittesting/BasicSample/SharedPreferencesHelper.java

Fixed 2 instances of javadoc {@code} tags (was written as @{code} )

Fixed {@code} javadoc tag

---

integration/ServiceTestRuleSample/app/src/androidTest/java/com/example/android/testing/ServiceTestRuleSample/LocalServiceTest.java
runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/CalculatorAddParameterizedTest.java
runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/CalculatorInstrumentationTest.java
runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/CalculatorTest.java
runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/OperationHintInstrumentationTest.java
runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/OperationHintLegacyInstrumentationTest.java
ui/espresso/BasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/ChangeTextBehaviorTest.java
ui/espresso/CustomMatcherSample/app/src/androidTest/java/com/example/android/testing/espresso/CustomMatcherSample/HintMatchersTest.java
ui/espresso/DataAdapterSample/app/src/androidTest/java/com/example/android/testing/espresso/DataAdapterSample/LongListActivityTest.java
ui/espresso/IdlingResourceSample/app/src/androidTest/java/com/example/android/testing/espresso/IdlingResourceSample/ChangeTextBehaviorTest.java
ui/espresso/IntentsAdvancedSample/app/src/androidTest/java/com/example/android/testing/espresso/intents/AdvancedSample/ImageViewerActivityTest.java
ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java
ui/espresso/MultiWindowSample/app/src/androidTest/java/com/example/android/testing/espresso/MultiWindowSample/MultiWindowTest.java
ui/espresso/RecyclerViewSample/app/src/androidTest/java/com/example/android/testing/espresso/RecyclerViewSample/RecyclerViewSampleTest.java
ui/espresso/WebBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/web/BasicSample/WebViewActivityTest.java
unit/BasicSample/app/src/test/java/com/example/android/testing/unittesting/BasicSample/EmailValidatorTest.java
unit/BasicSample/app/src/test/java/com/example/android/testing/unittesting/BasicSample/SharedPreferencesHelperTest.java
unit/BasicUnitAndroidTest/app/src/androidTest/java/com/example/android/testing/unittesting/basicunitandroidtest/LogHistoryAndroidUnitTest.java

Import android.support.test.filters.* across all projects instead of deprecated 
android.test.suitebuilder.annotation. Also, removed the <size>Test annotations from unit tests.

Updating <size>Test annotations to use new library.

---

WORKSPACE

`http_archive` is a lot more reliable than `git_repository`, and doesn't introduce a dependency on `git`. The native `git_repository` rule is also deprecated.

Use http_archive instead of git_repository to fetch dependencies

---

BUILD.bazel
WORKSPACE
ui/espresso/CustomMatcherSample/BUILD.bazel
ui/espresso/DataAdapterSample/BUILD.bazel
ui/espresso/IdlingResourceSample/BUILD.bazel
ui/espresso/IntentsAdvancedSample/BUILD.bazel
ui/espresso/IntentsBasicSample/BUILD.bazel
ui/espresso/MultiWindowSample/BUILD.bazel
ui/espresso/RecyclerViewSample/BUILD.bazel
ui/uiautomator/BasicSample/BUILD.bazel

`gmaven_rules` has a new `gmaven_artifact` macro to let users specify the actual Maven artifact string instead of target names. This PR updates the WORKSPACE commits and applies that macro across all `gmaven_rules` targets.

Update gmaven_rules target to use gmaven_artifact

---

WORKSPACE

Commented out the invalid `/path/to/sdk` declaration.

Make android_sdk_repository path more CI friendly

---

README.md
tools/bazel.rc

1) bazel.rc headless and gui configuration now pass --enable_display
test arg
2) Guide users to install Bazel 0.12.0
3) Added a command to query for all test targets

Improve bazel.rc config and README.md

---

WORKSPACE

@slinzner I've updated gmaven_rules to use Bazel's own HTTP fetching mechanism to download AARs, instead of using Maven. This should improve reliability and reduce flakiness in our CI.

Update gmaven_rules to drop the dependency on Maven

---

WORKSPACE

This sets the commit to https://github.com/android/android-test/commit/c69935b7c09aa2074588013b2159ba1972f31952 and fixes the Bazel build when using `--incompatible_remote_native_http_archive`.

Update android/android-test commit

---

WORKSPACE

tested on 0.19.0.
`bazel clean --expunge && bazel build //... --incompatible_remove_native_http_archive=true`
cc @meteorcloudy

Update android/android-test commit, actually fix Starlark http_archive incompatible change

---

ui/espresso/BasicSample/BUILD.bazel
ui/espresso/BasicSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/CustomMatcherSample/BUILD.bazel
ui/espresso/CustomMatcherSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/DataAdapterSample/BUILD.bazel
ui/espresso/DataAdapterSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/IdlingResourceSample/BUILD.bazel
ui/espresso/IdlingResourceSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/IntentsAdvancedSample/BUILD.bazel
ui/espresso/IntentsAdvancedSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/IntentsBasicSample/BUILD.bazel
ui/espresso/IntentsBasicSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/IntentsBasicSample/app/src/main/AppManifest.xml
ui/espresso/MultiWindowSample/BUILD.bazel
ui/espresso/MultiWindowSample/app/src/androidTest/AndroidManifest.xml
ui/espresso/RecyclerViewSample/BUILD.bazel
ui/espresso/RecyclerViewSample/app/src/androidTest/AndroidManifest.xml

Gradle tests:
```bash
$ for dir in BasicSample CustomMatcherSample DataAdapterSample IdlingResourceSample IntentsAdvancedSample IntentsBasicSample MultiWindowSample RecyclerViewSample
do 
pushd ui/espresso/$dir
./gradlew connectedAndroidTest
popd
done
...
$ echo $?
0
```
Bazel tests:
```
$ devbazel test //ui/espresso/... --incompatible_package_name_is_a_function=false 
INFO: Invocation ID: 33790409-cc14-4946-a162-754530b72389
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analysed 64 targets (0 packages loaded, 1967 targets configured).
INFO: Found 32 targets and 32 test targets...
INFO: Elapsed time: 0.585s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action …
```

Fix all Bazel-enabled tests to pass with Bazel on HEAD again

---

ui/uiautomator/BasicSample/BUILD.bazel
ui/uiautomator/BasicSample/app/src/androidTest/AndroidManifest.xml

Fixes issue that is also fixed in https://github.com/googlesamples/android-testing/pull/225 where the app under test and the test app shares the same package name, but that PR missed out on the UIAutomator test.
Tested:
```
$ cd ui/uiautomator/BasicSample
$ ./gradlew connectedAndroidTest
...
04:10:36 V/InstrumentationResultParser: Time: 22.398
04:10:36 V/InstrumentationResultParser: 
04:10:36 V/InstrumentationResultParser: OK (3 tests)
04:10:36 V/InstrumentationResultParser: 
04:10:36 V/InstrumentationResultParser: 
04:10:36 V/InstrumentationResultParser: INSTRUMENTATION_CODE: -1
04:10:36 V/InstrumentationResultParser: 
04:10:36 I/XmlResultReporter: XML test result file generated at /usr/local/google/home/jingwen/code/android-testing/ui/uiautomator/BasicSample/app/build/outputs/androidTest …
```

Fix package names of uiautomator.BasicSample test app and app under test

---

bazelci/buildkite-pipeline.yml

This configuration is currently hosted in https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/android-testing-postsubmit.yml. Now that the pipeline is stable, we can move it out to this repository and make changes here instead.
cc @meteorcloudy

Move Bazel CI configuration to this repository

---

WORKSPACE

This allows building with `--incompatible_no_transitive_load=true`

Bump android/android-test's dependency to use a release

---

bazelci/buildkite-pipeline.yml

Ubuntu 14.04 is about to be end-of-life and Bazel CI will stop supporting it shortly afterwards.
Context: https://groups.google.com/d/msg/bazel-dev/_D6XzfNkQQE/8TNKiNmsCAAJ

Don't test on Ubuntu 14.04

---

WORKSPACE

Make guice neverlink to not dex it. 
dx complains about dexing guice classes:
```
INFO: From Dexing external/maven/_dx/com_google_inject_guice_4_0/guice-4.0.jar_desugared.jar with applicable dexopts []:
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.google.inject.internal.cglib.core.$AbstractClassGenerator$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
```

Suppress dx spam on guice classes

---

WORKSPACE

Fixes #239 
```
$ bazel build --nobuild -k //... --incompatible_new_actions_api  --incompatible_no_transitive_loads  --incompatible_depset_is_not_iterable --incompatible_disable_deprecated_attr_params
INFO: Analyzed 73 targets (0 packages loaded, 0 targets configured).
INFO: Found 73 targets...
INFO: Elapsed time: 0.229s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```
fyi @laurentlb

Bump dependency on android-test to address Bazel incompatible changes

---

WORKSPACE

Bazel's CI has upgraded from 28.0.2 to 29.0.2 on the worker machines some time ago and this is causing the tests to fail.

Bump Android Build Tools to 29.0.2 in WORKSPACE

---

WORKSPACE

Apparently this project is not compatible with the newer build tools,
as the pipeline has been red on Linux and Windows since the upgrade:
https://buildkite.com/bazel/android-testing/builds/642
This reverts commit f08dda59e6e1c9dafd312b1b0c0ef1188bd6d9fe.

Revert "Bump Android Build Tools to 29.0.2 in WORKSPACE (#304)"

---

WORKSPACE

This platform is only valid on Linux machines, and breaks the build when
run from Windows or Mac.
The .bazelrc registers it as an execution platform when used with RBE.

Remove unconditional registration of :android_platform for execution.

---

BUILD.bazel

Bazel is migrating its RBE worker pool from n1 machines to e2. We created a new dedicated worker pool with n1 machines to support nested virtualization. This PR updates BRE config to target that dedicated worker pool.

RBE worker pool migration

---

WORKSPACE

Remove `build_tools_version` and `api_level` to let `android_sdk_repository` automatically select the latest installed version.
One of the fixes for https://github.com/bazelbuild/bazel/issues/13409#issuecomment-845265150

Remove build_tools_version and api_level

---

bazelci/buildkite-pipeline.yml

Ubuntu 16.04 is end-of-life, we're going to remove it from Bazel CI.
If you like you can add testing on `ubuntu2004` platform which we also support.

Remove ubuntu1604 from buildkite-pipeline.yml

---

bazelci/buildkite-pipeline.yml

Android Emulator adds complexity to the infrastructure, because the emulator requires access to the /dev/kvm device and enabled Nested Virtualization, which means that basically any CI job could get root on the host VM using that. The mitigations for that make other features very hard to implement.

Stop running android_instrumentation_test on Bazel CI

---

README.md

The default branch is `main` now, but links in `README.md` use `master` branch. This PR migrates those links from `master` to `main`.

Migrate links in README.md to main branch

---

ui/espresso/IntentsAdvancedSample/app/src/androidTest/java/com/example/android/testing/espresso/intents/AdvancedSample/ImageViewHasDrawableMatcher.java
ui/espresso/IntentsAdvancedSample/app/src/androidTest/java/com/example/android/testing/espresso/intents/AdvancedSample/ImageViewerActivityTest.java

Changed deprecated DiagnosingMatcher in BoundedDiagnosingMatcher. Changed in IntentsTestRule in ActivityScenarioRule, used Intents.init() and Intents.release()

Fixed deprecations in IntentsAdvancedSample tests

---

ui/espresso/DataAdapterSample/app/build.gradle
ui/espresso/EspressoDeviceSample/app/build.gradle
ui/espresso/IdlingResourceSample/app/build.gradle
ui/espresso/IntentsAdvancedSample/app/build.gradle
ui/espresso/IntentsBasicSample/app/build.gradle
ui/espresso/MultiProcessSample/app/build.gradle
ui/espresso/MultiWindowSample/app/build.gradle
ui/espresso/RecyclerViewSample/app/build.gradle
ui/espresso/WebBasicSample/app/build.gradle
ui/uiautomator/BasicSample/app/build.gradle
unit/BasicSample/app/build.gradle
unit/BasicUnitAndroidTest/app/build.gradle

The previous function style is deprecated.
See https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-api/src/main/java/com/android/build/api/dsl/CommonExtension.kt;l=723?q=buildToolsVersion&ss=android-studio.

Migrate buildToolVersion to property style
