android/testing-samples

- README.md
- build.gradle
- espresso/BasicSample/app/build.gradle
- espresso/CustomMatcherSample/app/build.gradle
- espresso/DataAdapterSample/app/build.gradle
- espresso/MultiWindowSample/app/build.gradle
- testrunner/AndroidJunitRunnerSample/app/build.gradle
> Gradle updates

- README.md
- build.gradle
- espresso/BasicSample/app/build.gradle
- espresso/CustomMatcherSample/app/build.gradle
- espresso/DataAdapterSample/app/build.gradle
- espresso/MultiWindowSample/app/build.gradle
- testrunner/AndroidJunitRunnerSample/app/build.gradle
Reverts googlesamples/android-testing#8
This is a good idea for building and executing all the samples from the root directory but it breaks the execution of an individual sample.
> Revert "Gradle updates"

- unittesting/BasicSample/app/src/main/java/com/example/android/testing/unittesting/BasicSample/EmailValidator.java
- unittesting/BasicSample/app/src/test/java/com/example/android/testing/unittesting/BasicSample/EmailValidatorTest.java
The unit tests validates the regex in the application under test. This
regex should be part of the app and not the test.
> Moves the email regex to the app

- runner/AndroidJunitRunnerSample/README.md
- ui/espresso/BasicSample/README.md
- ui/espresso/BasicSampleBundled/README.md
- ui/espresso/CustomMatcherSample/README.md
- ui/espresso/DataAdapterSample/README.md
- ui/espresso/IntentsAdvancedSample/README.md
- ui/espresso/IntentsBasicSample/README.md
- ui/espresso/MultiWindowSample/README.md
- ui/espresso/WebBasicSample/README.md
issue #59  Updated Readme.md with the description of http://google.github.io/android-testing-support-library/docs/espresso/setup/index.html#setup-your-test-environment to disable animations
> Update README.md broken link

- integration/ServiceTestRuleSample/build.gradle
- runner/AndroidJunitRunnerSample/build.gradle
- ui/espresso/BasicSample/build.gradle
- ui/espresso/CustomMatcherSample/build.gradle
- ui/espresso/DataAdapterSample/build.gradle
- ui/espresso/IntentsAdvancedSample/build.gradle
- ui/espresso/IntentsBasicSample/build.gradle
- ui/espresso/MultiWindowSample/build.gradle
- ui/espresso/WebBasicSample/build.gradle
- ui/uiautomator/BasicSample/build.gradle
- unit/BasicSample/app/build.gradle
- unit/BasicSample/build.gradle
- unit/BasicUnitAndroidTest/build.gradle
> Upgrade all gradle version from alpha6 to beta2

- unit/BasicSample/app/src/main/java/com/example/android/testing/unittesting/BasicSample/EmailValidator.java
- unit/BasicSample/app/src/main/java/com/example/android/testing/unittesting/BasicSample/SharedPreferencesHelper.java
- unit/BasicSample/app/src/test/java/com/example/android/testing/unittesting/BasicSample/EmailValidatorTest.java
- unit/BasicSample/app/src/test/java/com/example/android/testing/unittesting/BasicSample/SharedPreferencesHelperTest.java
removed 3 unused imports , 1 unused javadoc '@param' tag
> removed unused imports, unused '@param' tag in javadoc

- integration/ServiceTestRuleSample/build.gradle
- integration/ServiceTestRuleSample/gradle/wrapper/gradle-wrapper.properties
- runner/AndroidJunitRunnerSample/build.gradle
- runner/AndroidJunitRunnerSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/BasicSample/build.gradle
- ui/espresso/BasicSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/CustomMatcherSample/build.gradle
- ui/espresso/CustomMatcherSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/DataAdapterSample/build.gradle
- ui/espresso/DataAdapterSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/IdlingResourceSample/build.gradle
- ui/espresso/IdlingResourceSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/IntentsAdvancedSample/build.gradle
- ui/espresso/IntentsAdvancedSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/IntentsBasicSample/build.gradle
- ui/espresso/IntentsBasicSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/MultiWindowSample/build.gradle
- ui/espresso/MultiWindowSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/RecyclerViewSample/build.gradle
- ui/espresso/RecyclerViewSample/gradle/wrapper/gradle-wrapper.properties
- ui/espresso/WebBasicSample/build.gradle
- ui/espresso/WebBasicSample/gradle/wrapper/gradle-wrapper.properties
- ui/uiautomator/BasicSample/build.gradle
- ui/uiautomator/BasicSample/gradle/wrapper/gradle-wrapper.properties
- unit/BasicSample/build.gradle
- unit/BasicSample/gradle/wrapper/gradle-wrapper.properties
- unit/BasicUnitAndroidTest/build.gradle
- unit/BasicUnitAndroidTest/gradle/wrapper/gradle-wrapper.properties
Gradle: 3.0
Build Tools: 25.0.0
AGP: 2.3.2
> Update Gradle/BuildTools/Plugin version

- ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java
> Fix a typo

- WORKSPACE
> Update @android_test_support to the latest commit

- WORKSPACE
I messed up the commits in #169. This PR fixes it.
> Fix commits in WORKSPACE

- ui/espresso/BasicSample/BUILD.bazel
- ui/espresso/CustomMatcherSample/BUILD.bazel
- ui/espresso/DataAdapterSample/BUILD.bazel
- ui/espresso/IdlingResourceSample/BUILD.bazel
- ui/espresso/IntentsAdvancedSample/BUILD.bazel
- ui/espresso/IntentsBasicSample/BUILD.bazel
- ui/espresso/MultiWindowSample/BUILD.bazel
- ui/espresso/RecyclerViewSample/BUILD.bazel
- ui/uiautomator/BasicSample/BUILD.bazel
> Bazel android_instrumentation_test: Test against API levels 19 to 23.

- README.md
- WORKSPACE
- tools/bazel.rc
> Update ATSL commit to include the fix for sandboxed tests

- BUILD.bazel
- ui/espresso/IdlingResourceSample/BUILD.bazel
- ui/espresso/IntentsAdvancedSample/BUILD.bazel
- ui/espresso/IntentsBasicSample/BUILD.bazel
- ui/espresso/RecyclerViewSample/BUILD.bazel
See: https://github.com/bazelbuild/bazel/issues/5855
> Update espresso version

- WORKSPACE
- common_defs.bzl
Fixes https://github.com/googlesamples/android-testing/issues/213
cc @meteorcloudy @mhlopko 
TESTED=bazel test //ui/... with Bazel 0.19.0
> Use Starlark http_archive and update androidx.test dependencies to their stable versions

- README.md
Just made https://buildkite.com/bazel/android-testing public.
> Update README with Bazel CI badge and target labels

- ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java
> Use GrantPermissionRule in IntentsBasicSample.

- WORKSPACE
See https://github.com/bazelbuild/bazel/issues/6799 for more details
> Stop using maven_jar in android-testing

- WORKSPACE
- common_defs.bzl
- ui/espresso/CustomMatcherSample/BUILD.bazel
- ui/espresso/IntentsBasicSample/BUILD.bazel
Update dependency versions and add robolectric deps to shared tests
Fixes https://github.com/googlesamples/android-testing/issues/267
> Fix Bazel builds and tests

- .bazelrc
- WORKSPACE
cc @laurentlb @brandjon 
Fixes https://github.com/googlesamples/android-testing/issues/266
> Bump android-test and add --host_force_python to be compatible with --incompatible_use_python_toolchains

- WORKSPACE
- bazelci/buildkite-pipeline.yml
- ui/espresso/AccessibilitySample/BUILD.bazel
Fixes https://github.com/android/testing-samples/issues/303
Also don't test it on CI yet because of the "No virtual method checkAndReturnResults" error: https://github.com/android/android-test/issues/376
> Fix AccessibilitySample build

- .bazelrc
- BUILD.bazel
- WORKSPACE
- bazelci/buildkite-pipeline.yml
> Add support for building android_device and testing android_instrumentation_test emulator tests on RBE

- ui/espresso/BasicSample/app/build.gradle
- ui/espresso/BasicSample/build.gradle
- ui/espresso/FragmentScenarioSample/build.gradle
This makes it possible to run the Kotlin tests in Android Studio.
> Update to Kotlin 1.3.72 in some testing samples

- ui/espresso/RecyclerViewSample/app/src/androidTest/java/com/example/android/testing/espresso/RecyclerViewSample/RecyclerViewSampleTest.java
A simple example showing how to just check if an item exists.
> Add itemWithText_exists

- ui/espresso/AccessibilitySample/app/build.gradle
- ui/espresso/AccessibilitySample/build.gradle
- ui/espresso/AccessibilitySample/gradle/wrapper/gradle-wrapper.properties
See https://github.com/android/android-test/issues/861
> Workaround for org.checkerframework duplicate class errors.

- ui/espresso/ScreenshotSample/build.gradle
- ui/espresso/ScreenshotSample/gradle/wrapper/gradle-wrapper.properties
Thi change was mistakenly omitted from  #407
> Update screenshot sample to AGP 7.2.0-alpha03.

- runner/AndroidTestOrchestratorWithTestCoverageSample/build.gradle
To be compatible with AS Bumblebee 2021.1.1 Patch 1
> build: upgrade AGP from 7.1.0-alpha12 to 7.1.1

- ui/espresso/AccessibilitySample/build.gradle
- ui/espresso/BasicSample/build.gradle
- ui/espresso/CustomMatcherSample/build.gradle
- ui/espresso/DataAdapterSample/build.gradle
- ui/espresso/FragmentScenarioSample/build.gradle
- ui/espresso/IntentsBasicSample/build.gradle
- update_versions.sh
> Bump dependency versions

- ui/espresso/AccessibilitySample/build.gradle
- ui/espresso/BasicSample/build.gradle
- ui/espresso/CustomMatcherSample/build.gradle
- ui/espresso/DataAdapterSample/build.gradle
- ui/espresso/FragmentScenarioSample/build.gradle
- ui/espresso/IntentsBasicSample/build.gradle
- update_versions.sh
> Bump Robolectric to 4.9

- ui/espresso/AccessibilitySample/build.gradle
- ui/espresso/BasicSample/build.gradle
- ui/espresso/CustomMatcherSample/build.gradle
- ui/espresso/DataAdapterSample/build.gradle
- ui/espresso/EspressoDeviceSample/build.gradle
- ui/espresso/FragmentScenarioSample/build.gradle
- ui/espresso/IntentsBasicSample/build.gradle
This is needed to support running on JDK 20.
By mistake this change was somehow not included in PR #485
> Upgrade to robolectric 4.10.3.
